pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [NomadBlacky]
      label:
        add: [dependencies]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - check-success=Scala CI / scalafmt
      - check-success=Scala CI / test (8)
      - check-success=Scala CI / test (11)
    actions:
      merge:
        method: squash
