cache:
  paths:
    - .sbt
    - .ivy2

.test:
  stage: test
  script:
    - sbt -sbt-dir .sbt -ivy .ivy2 -mem 2048 clean +test

.jdk8:
  image: hseeberger/scala-sbt:8u212_1.2.8_2.12.8

.jdk11:
  image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8

test jdk8:
  extends:
    - .test
    - .jdk8

test jdk11:
  extends:
    - .test
    - .jdk11

scalafmt:
  extends: .jdk8
  stage: test
  script:
    - sbt -sbt-dir .sbt -ivy .ivy2 -mem 2048 clean scalafmtCheckAll scalafmtSbtCheck
