version: 2.1

.java_tool_options: &java_tool_options
  JAVA_TOOL_OPTIONS: -Xmx3200m

commands:
  sbt_test:
    parameters:
      command:
        type: string
        default: sbt clean +test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: << parameters.command >>
      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2
          key: v1-dependencies--{{ checksum "build.sbt" }}

jobs:
  test_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.8
    environment:
      <<: *java_tool_options
    steps:
      - sbt_test

  test_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8
    environment:
      <<: *java_tool_options
    steps:
      - sbt_test

  test_scalafmt:
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.8
    environment:
      <<: *java_tool_options
    steps:
      - sbt_test:
          command: sbt clean scalafmtCheckAll scalafmtSbtCheck

workflows:
  version: 2
  test_all:
    jobs:
      - test_jdk8
      - test_jdk11
      - test_scalafmt
